spring:
  profiles:
    active: dev
---
server:
  port: 7001
spring:
  application:
    name: gofashion-cloud-commodity-producer
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/gofashion
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 20
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
eureka:
  instance:
    instance-id: gofashion-cloud-commodity-producer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://39.105.144.41:6001/eureka/
---
spring:
  zipkin:
    base-url: http://116.62.167.249:6601
  sleuth:
    sampler:
       percentage: 1.0
  rabbitmq:
    host: 39.105.144.41
    port: 5672
    username: gofashion
    password: gofashion
    virtual-host: /goFashion
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1

logging:
    level: info




